### ISSUE TITLE
Crash when building the CDGraph of a function with an unreachable block

### ISSUE THREAD

**Issue by robcasloz** [compor/pedigree#3]
Hi @compor, sorry to bother you again ;)

When building the CDGraph of the attached `foo` function ([foo.ll.zip](https://github.com/compor/Pedigree/files/3240474/foo.ll.zip)), `opt` crashes with the following error message:

```
opt: llvm/include/Pedigree/Analysis/PostDominanceFrontier.hpp:116: const pedigree::PostDominanceFrontierBase::DomSetType &pedigree::PostDominanceFrontierBase<llvm::BasicBlock>::calculate(const pedigree::PostDominanceFrontierBase::DomTreeT &) [BlockT = llvm::BasicBlock]: Assertion `blockRoot && "Only one entry block for post domfronts!"' failed.
```

This issue is probably related to #1  as  `foo` also contains an unreachable block. It is not a regression introduced by #2, LLVM crashes as well before merging it. The problem disappears if I run `-unreachableblockelim` before. An alternative fix would be to just make all Pedigree passes dependent on this pass.

**How to reproduce**
1. Assert that running `opt -S -pedigree-cdg foo.ll` does not yield a crash.

Thanks again!

**Comment by compor** [comment]
Hey again :wink: 

Please have a look at PR #4. It does not work :disappointed: 

My understanding is that although there is a limited support for requiring *transformations* in analyses (see a working example [here][1]), in this case, a similar attempt fails because this transform is exposed as a machine (i.e. operating on machine level IR) pass, thus it cannot be referenced earlier than that as in the working [example][1].

Therefore, either we should run this manually or use the following fallback in the relevant method in the post-dominance frontier builder:
- If the root block is empty (at this [point][2]), then just use the entry block. 

The second idea feels like we are trying to herd cats, but I can't think of anything else ATM. What do you think?

[1]: https://github.com/compor/SimplifyLoopExitsFront/blob/61020067adf0ce80d29534fed486aedcdea656f6/lib/SimplifyLoopExitsFrontPass.cpp#L312

[2]: https://github.com/compor/Pedigree/blob/df068815ca7d37f8fae3f3f61b90ae2e755361b6/include/Pedigree/Analysis/PostDominanceFrontier.hpp#L108

**Comment by robcasloz** [comment]
I see. If implementing the check you mention is easy and fixes this problem, it might be worth trying that out first. But it is really your choice ;)
